# ⚽ Mission 07: Soccer Data Investigation

Welcome back, Lead Data Analyst of **Artin FC**!

Yesterday, in Mission 6, you built the decision engine of your AI Soccer Coach. By combining the tools in your coach_toolbox library, your AI Coach learned how to analyze players and generate coaching recommendations automatically.

Today, your role is changing once again.

Before coaches can make great decisions—or data scientists can build beautiful dashboards—they must first organize, explore, and understand their data. Professional soccer clubs such as Manchester City, Barcelona, Liverpool, and Real Madrid rely on Sports Data Analysts to transform thousands of rows of player statistics into meaningful insights that help coaches improve team performance.

Today, you will become one of those analysts.

Using the Artin FC dataset, you will learn how to work with pandas DataFrames like a professional. You'll sort players by performance, filter the data to answer coaching questions, calculate team statistics, create new data columns, and build a complete team analysis report. By the end of this mission, you'll be able to investigate your team's data quickly and confidently—just like a real soccer data analyst.

The visualization dashboard will come in the next mission. First, every great analyst must learn how to understand the data before presenting it.

### Difficulty :
Intermediate

### Duration:
3 Hours

### Skills Needed:
- Unpacking player lists & dictionary key structures (Missions 1 & 2)
- Designing manual accumulator for loops (Missions 3 & 4)
- Translating technical requirements into Python function logic (Mission 4)
- Building and using python libraries (Mission 5 & 6)

---
## 🎯 Learning Objectives
By the end of this mission, you will be able to:

- Create and explore pandas DataFrames
- Select rows and columns from a dataset
- Filter players using one or more conditions
- Sort players by different statistics
- Calculate summary statistics and answer coaching questions
- Create new calculated columns using your own Python functions
- Use apply() to combine pandas with your coach_toolbox library
- Generate a complete statistical report for Artin FC using pandas

---

## 🔄 Milestone 1: Mission 06 Quick Refresh

Let's upload your developed library (`coach_toolbox.py` module file) to your Google Colab so you can import code from it.

In [5]:
# ==========================================
# Mission Setup
# ==========================================

# Upload coach_toolbox.py from your computer
from google.colab import files

uploaded = files.upload()

Saving coach_toolbox_v2.py to coach_toolbox_v2.py

Now let's load our complete **Artin_FC_v2** dataset containing the 4-game historical lists AND the 5 skill ratings:

In [11]:
Artin_FC_v2 = [
    {
        "name": "Artin", "position": "Forward", "age": 11,
        "goals": [2, 1, 0, 3], "assists": [1, 0, 2, 1],
        "passes_completed": [25, 30, 22, 28], "total_passes": [28, 32, 26, 30],
        "passing": 85, "defending": 45, "stamina": 90, "speed": 92, "shooting": 88
    },
    {
        "name": "Messi", "position": "Forward", "age": 38,
        "goals": [2, 3, 1, 2], "assists": [1, 1, 2, 0],
        "passes_completed": [40, 42, 38, 45], "total_passes": [42, 43, 40, 46],
        "passing": 95, "defending": 38, "stamina": 85, "speed": 89, "shooting": 96
    },
    {
        "name": "Jahanbakhsh", "position": "Midfielder", "age": 32,
        "goals": [0, 1, 0, 1], "assists": [1, 0, 1, 0],
        "passes_completed": [20, 18, 22, 19], "total_passes": [25, 24, 26, 23],
        "passing": 82, "defending": 50, "stamina": 80, "speed": 85, "shooting": 80
    },
    {
        "name": "Maradona", "position": "Midfielder", "age": 12,
        "goals": [1, 2, 1, 1], "assists": [2, 1, 3, 1],
        "passes_completed": [35, 38, 32, 36], "total_passes": [38, 40, 35, 39],
        "passing": 94, "defending": 40, "stamina": 82, "speed": 88, "shooting": 92
    },
    {
        "name": "Zidane", "position": "Midfielder", "age": 13,
        "goals": [0, 1, 0, 0], "assists": [1, 2, 1, 2],
        "passes_completed": [38, 42, 40, 41], "total_passes": [40, 45, 42, 44],
        "passing": 92, "defending": 65, "stamina": 84, "speed": 80, "shooting": 84
    },
    {
        "name": "Iniesta", "position": "Midfielder", "age": 12,
        "goals": [0, 0, 1, 0], "assists": [2, 1, 1, 1],
        "passes_completed": [45, 48, 42, 46], "total_passes": [47, 50, 45, 48],
        "passing": 90, "defending": 70, "stamina": 86, "speed": 78, "shooting": 75
    },
    {
        "name": "Marcelo", "position": "Defender", "age": 11,
        "goals": [0, 1, 0, 0], "assists": [1, 1, 2, 0],
        "passes_completed": [30, 32, 28, 34], "total_passes": [34, 36, 32, 38],
        "passing": 84, "defending": 78, "stamina": 88, "speed": 86, "shooting": 70
    },
    {
        "name": "Pique", "position": "Defender", "age": 14,
        "goals": [0, 0, 1, 0], "assists": [0, 0, 0, 1],
        "passes_completed": [22, 24, 20, 25], "total_passes": [25, 26, 22, 28],
        "passing": 78, "defending": 88, "stamina": 80, "speed": 72, "shooting": 65
    },
    {
        "name": "Maldini", "position": "Defender", "age": 15,
        "goals": [0, 0, 0, 0], "assists": [0, 0, 1, 0],
        "passes_completed": [18, 22, 21, 19], "total_passes": [20, 24, 22, 21],
        "passing": 75, "defending": 94, "stamina": 85, "speed": 82, "shooting": 60
    },
    {
        "name": "Dani Alves", "position": "Defender", "age": 13,
        "goals": [0, 0, 0, -1], "assists": [2, 1, 1, 2],
        "passes_completed": [32, 35, 30, 33], "total_passes": [36, 38, 34, 37],
        "passing": 86, "defending": 80, "stamina": 89, "speed": 88, "shooting": 72
    },
    {
        "name": "Beiranvand", "position": "Goalkeeper", "age": 12,
        "goals": [0, 0, 0, 0], "assists": [0, 0, 0, 0],
        "passes_completed": [15, 12, 18, 14], "total_passes": [22, 20, 25, 21],
        "passing": 70, "defending": 15, "stamina": 75, "speed": 65, "shooting": 10
    }
]

print("💪 Complete Team Database Version 2.0 active with", len(Artin_FC_v2), "players!")

💪 Complete Team Database Version 2.0 active with 11 players!

Let's test if we can successfully call the functions we exported into `coach_toolbox_v2.py` yesterday. Run this test block:

In [12]:
# Let's verify our custom functions work!
from coach_toolbox_v2 import calculate_overall_rating, generate_ai_tactical_recommendation

print("🔥 Toolbox loaded! Artin Rating:", calculate_overall_rating(Artin_FC_v2[0]))
print("🔥 Tactical recommendation for Artin:", generate_ai_tactical_recommendation(Artin_FC_v2[0]))

🔥 Toolbox loaded! Artin Rating: 78.75
🔥 Tactical recommendation for Artin: Winger breakout threat. Focus on flank overlaps.

You successfully solved your bonus challenge; an analysis_report-v2(team) function. Let's review and test it again.

In [13]:
from coach_toolbox_v2 import *

def analysis_report_v2(team):

    total_players = len(team)
    need_rest = 0
    needs_passing = 0
    ready = 0

    for player in team:
        if needs_rest(player):
            need_rest += 1

    for player in team:
        if needs_passing_practice(player):
            needs_passing += 1

    for player in team:
        if coach_decision(player) == "Ready for Match.":
            ready += 1

    report = {
        "Number of players": total_players,
        "Number needing rest": need_rest,
        "Number needing passing practice": needs_passing,
        "Number ready for match": ready
    }

    return report

In [14]:
team_report = analysis_report_v2(Artin_FC_v2)
print(team_report)

{'Number of players': 11, 'Number needing rest': 2, 'Number needing passing practice': 1, 'Number ready for match': 8}

---

## 🧱 Part 1: Meet Your Team Dashboard

Instead of managing a giant list of curly-braces and lists, let's load Artin_FC_v2 dataset into the data science standard spreadsheet grid: a **Pandas DataFrame**.

In [15]:
import pandas as pd

# Convert our player dictionaries list to a Pandas DataFrame
df = pd.DataFrame(Artin_FC_v2)

# Show the entire table!
df

,name,position,age,goals,assists,passes_completed,total_passes,passing,defending,stamina,speed,shooting
0,Artin,Forward,11,"[2, 1, 0, 3]","[1, 0, 2, 1]","[25, 30, 22, 28]","[28, 32, 26, 30]",85,45,90,92,88
1,Messi,Forward,38,"[2, 3, 1, 2]","[1, 1, 2, 0]","[40, 42, 38, 45]","[42, 43, 40, 46]",95,38,85,89,96
2,Jahanbakhsh,Midfielder,32,"[0, 1, 0, 1]","[1, 0, 1, 0]","[20, 18, 22, 19]","[25, 24, 26, 23]",82,50,80,85,80
3,Maradona,Midfielder,12,"[1, 2, 1, 1]","[2, 1, 3, 1]","[35, 38, 32, 36]","[38, 40, 35, 39]",94,40,82,88,92
4,Zidane,Midfielder,13,"[0, 1, 0, 0]","[1, 2, 1, 2]","[38, 42, 40, 41]","[40, 45, 42, 44]",92,65,84,80,84
5,Iniesta,Midfielder,12,"[0, 0, 1, 0]","[2, 1, 1, 1]","[45, 48, 42, 46]","[47, 50, 45, 48]",90,70,86,78,75
6,Marcelo,Defender,11,"[0, 1, 0, 0]","[1, 1, 2, 0]","[30, 32, 28, 34]","[34, 36, 32, 38]",84,78,88,86,70
7,Pique,Defender,14,"[0, 0, 1, 0]","[0, 0, 0, 1]","[22, 24, 20, 25]","[25, 26, 22, 28]",78,88,80,72,65
8,Maldini,Defender,15,"[0, 0, 0, 0]","[0, 0, 1, 0]","[18, 22, 21, 19]","[20, 24, 22, 21]",75,94,85,82,60
9,Dani Alves,Defender,13,"[0, 0, 0, -1]","[2, 1, 1, 2]","[32, 35, 30, 33]","[36, 38, 34, 37]",86,80,89,88,72
10,Beiranvand,Goalkeeper,12,"[0, 0, 0, 0]","[0, 0, 0, 0]","[15, 12, 18, 14]","[22, 20, 25, 21]",70,15,75,65,10

In [16]:
# Show the first few rows of our table!
df.head()

,name,position,age,goals,assists,passes_completed,total_passes,passing,defending,stamina,speed,shooting
0,Artin,Forward,11,"[2, 1, 0, 3]","[1, 0, 2, 1]","[25, 30, 22, 28]","[28, 32, 26, 30]",85,45,90,92,88
1,Messi,Forward,38,"[2, 3, 1, 2]","[1, 1, 2, 0]","[40, 42, 38, 45]","[42, 43, 40, 46]",95,38,85,89,96
2,Jahanbakhsh,Midfielder,32,"[0, 1, 0, 1]","[1, 0, 1, 0]","[20, 18, 22, 19]","[25, 24, 26, 23]",82,50,80,85,80
3,Maradona,Midfielder,12,"[1, 2, 1, 1]","[2, 1, 3, 1]","[35, 38, 32, 36]","[38, 40, 35, 39]",94,40,82,88,92
4,Zidane,Midfielder,13,"[0, 1, 0, 0]","[1, 2, 1, 2]","[38, 42, 40, 41]","[40, 45, 42, 44]",92,65,84,80,84

In [17]:
df.tail()

,name,position,age,goals,assists,passes_completed,total_passes,passing,defending,stamina,speed,shooting
6,Marcelo,Defender,11,"[0, 1, 0, 0]","[1, 1, 2, 0]","[30, 32, 28, 34]","[34, 36, 32, 38]",84,78,88,86,70
7,Pique,Defender,14,"[0, 0, 1, 0]","[0, 0, 0, 1]","[22, 24, 20, 25]","[25, 26, 22, 28]",78,88,80,72,65
8,Maldini,Defender,15,"[0, 0, 0, 0]","[0, 0, 1, 0]","[18, 22, 21, 19]","[20, 24, 22, 21]",75,94,85,82,60
9,Dani Alves,Defender,13,"[0, 0, 0, -1]","[2, 1, 1, 2]","[32, 35, 30, 33]","[36, 38, 34, 37]",86,80,89,88,72
10,Beiranvand,Goalkeeper,12,"[0, 0, 0, 0]","[0, 0, 0, 0]","[15, 12, 18, 14]","[22, 20, 25, 21]",70,15,75,65,10

### 💡 Under the Hood: What is a DataFrame?
* **Rows:** Each row (horizontal) represents a single **individual player**.
* **Columns:** Each column (vertical) represents a specific **attribute or metric** of information about that player.

### 🗺️ Introduction: How Does .loc[] Work?
 we need to learn how to navigate our Pandas spreadsheet using a tool called .loc[] (which stands for Location).Think of a DataFrame like a giant coordinate map or a grid of player cards. Every row has an Index Number (starting at 0), and every column has a Name Label.To pull any piece of data out of the grid, we give .loc[] a clean rule:$$\text{df.loc[ Row Index Number , Column Name Label ]}$$Let's look at a few quick examples of how the coach can use .loc[] to read player profiles:

In [18]:
# Example 1: Grab the name of the player on Row 0
print(df.loc[0, "name"])  # Outputs: Artin

Artin

In [19]:
# Example 2: Grab the position of the player on Row 1
print(df.loc[1, "position"])  # Outputs: Messi

Forward

In [20]:
# Example 3: Grab the stamina rating of the player on Row 4
print(df.loc[4, "stamina"])  # Outputs: Zidane

84

In [21]:
# Example 3: Grab the passing rating of the player on Row 8
print(df.loc[8, "passing"])

75

In [22]:
df["stamina"]

0     90
1     85
2     80
3     82
4     84
5     86
6     88
7     80
8     85
9     89
10    75
Name: stamina, dtype: int64

### 📈 Part 2 - Statistical Outputs
* **`count`**: The total count of valid items present in that column.
* **`mean`**: The mathematical average value of the column metrics.
* **`std`**: Standard Deviation (tells you how spread out the values are from the average. High deviation means the team has a wide range of skill ratings; low means they have uniform skill ranges).
* **`min`**: The minimum value recorded in that column.
* **`max`**: The maximum value recorded in that column.

In [23]:
df["stamina"].count()

np.int64(11)

In [24]:
df["stamina"].mean()

np.float64(84.0)

In [25]:
df["stamina"].min()

75

In [26]:
df["stamina"].max()

90

Find the minimum and maximum speed among players

In [27]:
# Your code here
#df["speed"].max()
df["speed"].min()

65

Find average shooting among players

In [28]:
df["shooting"].mean()

np.float64(72.0)

---

## 🔍 Part 3 - Become a Data Detective

Let's write direct query calculations to answer immediate coaching questions about our player group:

In [29]:
# 1. How many players do we have on the roster?
print("👥 Roster Size:", len(df))

👥 Roster Size: 11

In [30]:
# 2. What is the average stamina rating across our whole team?
print("🫁 Average Stamina:", df["stamina"].mean())

🫁 Average Stamina: 84.0

In [31]:
# 3. Who is our youngest and oldest player?
print("👶 Youngest Age:", df["age"].min())
print("🧓 Oldest Age:", df["age"].max())

👶 Youngest Age: 11
🧓 Oldest Age: 38

In [32]:
# 4. What is the most goals scored in a single match by a player?
# (Since goals is a list of 4 match scores, let's look at who scored the highest individual total)
df['total_goals'] = df['goals'].apply(sum)
max_goals_idx = df['total_goals'].idxmax()
print(f"⚽ Top Goal Scorer: {df.loc[max_goals_idx, 'name']} with {df.loc[max_goals_idx, 'total_goals']} total goals!")

⚽ Top Goal Scorer: Messi with 8 total goals!

### Hunting Down the Top Scorer (Step-by-Step)
we are going to learn how to load your custom function from yesterday's library, map it onto our DataFrame spreadsheet, find the highest value, and introduce the ultimate data mapping tool: .loc (Location Selection).

#### 📦 Step 1: Import the Custom Function from your Library
Before Pandas can do any work, we need to fetch our specialized calculation tool from the external coach_toolbox.py library file.

In [33]:
from coach_toolbox_v2 import calculate_goals

print(" goal calculator successfully imported from coach_toolbox!")

 goal calculator successfully imported from coach_toolbox!

#### 🧬 Step 2: Use .apply() to Create the New Column
Now, we want to run your function across every single row of our DataFrame. Instead of writing a slow for loop, Pandas has a superpower called .apply().

We pass our custom function inside .apply() and tell it axis=1 (which means "apply this across every horizontal row").

In [34]:
# Create a brand new column named 'total_goals' by passing the player rows through your function
df['total_goals'] = df.apply(calculate_goals, axis=1)

# Let's peek at our updated team grid!
df[['name', 'position', 'total_goals']]

           name    position  total_goals
0         Artin     Forward            6
1         Messi     Forward            8
2   Jahanbakhsh  Midfielder            2
3      Maradona  Midfielder            5
4        Zidane  Midfielder            1
5       Iniesta  Midfielder            1
6       Marcelo    Defender            1
7         Pique    Defender            1
8       Maldini    Defender            0
9    Dani Alves    Defender           -1
10   Beiranvand  Goalkeeper            0

*Look at that! Pandas automatically looped through the team and added a clean total number right next to each player's name.*

#### 🔢 Step 3: Find the Row Label Using idxmax()
Now that we have a column of numbers, we use idxmax() (which stands for "Index of the Maximum").

idxmax() scans down the total_goals column, finds the largest number, and returns the Row Index Number where that record lives!

In [35]:
# Ask Pandas for the exact row index label where the highest value lives
highest_row_index = df['total_goals'].idxmax()

print(f"🎯 The top scorer is located at row index number: {highest_row_index}")

🎯 The top scorer is located at row index number: 1

#### 👑 Step 4: Use .loc[] to Print the Winner's Card
Now we combine everything! We hand our newly discovered best_row_index straight to .loc[] to instantly extract their identity and final score:

In [36]:
df.loc[highest_row_index, "name"]

'Messi'

In [37]:
# Pass the row index into .loc[row, column] to extract the data cards
top_scorer_name = df.loc [highest_row_index, 'name']
highest_goals = df.loc[highest_row_index, 'total_goals']


# Print the final official scoreboard report!
print("==================================================")
print(f"🏆 GOLDEN BOOT WINNER")
print("==================================================")
print(f"Top Scorer Identity: {top_scorer_name}")
print(f"Total Output Score:  {highest_goals} Goals")
print("==================================================")

==================================================
🏆 GOLDEN BOOT WINNER
==================================================
Top Scorer Identity: Messi
Total Output Score:  8 Goals
==================================================

In [38]:
# Combined code for hunting the top scorer

# Step 1: Import the custom tool from your library
from coach_toolbox_v2 import calculate_goals

# Step 2: Apply across rows to create our total goals column
df['total_goals'] = df.apply(calculate_goals, axis=1)

# Step 3: Find the exact row index of the highest value using idxmax()
top_player_row = df['total_goals'].idxmax()

# Step 4: Use .loc[row, column] to pull the name and score instantly
top_scorer_identity = df.loc[top_player_row, 'name']
highest_score = df.loc[top_player_row, 'total_goals']

# Display our official analytics report!
print(f"⚽ Top Goal Scorer: {top_scorer_identity} with {highest_score} total goals!")

⚽ Top Goal Scorer: Messi with 8 total goals!

### Challenge1- Find who assisted most? how many assists in total?

In [39]:
from coach_toolbox_v2 import *

df["total_assists"] = df.apply(calculate_assists, axis=1)

top_assister_row = df["total_assists"].idxmax()

top_assister_identity = df.loc[top_assister_row, "name"]
highest_assist_score = df.loc[top_assister_row, "total_assists"]

print(f"⚽ Top Assister: {top_assister_identity} with {highest_assist_score} total assists!")

⚽ Top Assister: Maradona with 7 total assists!

---

## 📈 Build Your First Dashboard

Running `df.describe()` automatically computes a comprehensive analytical breakdown of every numerical column in your dataset!

In [40]:
# Generate automated dataset overview metrics
df.describe()

,age,passing,defending,stamina,speed,shooting,total_goals,total_assists
count,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000
mean,16.636364,84.636364,60.272727,84.000000,82.272727,72.000000,2.181818,3.636364
std,9.254974,7.990904,24.540134,4.472136,8.088151,23.430749,2.857208,2.335497
min,11.000000,70.000000,15.000000,75.000000,65.000000,10.000000,-1.000000,0.000000
25%,12.000000,80.000000,42.500000,81.000000,79.000000,67.500000,0.500000,1.500000
50%,13.000000,85.000000,65.000000,85.000000,85.000000,75.000000,1.000000,4.000000
75%,14.500000,91.000000,79.000000,87.000000,88.000000,86.000000,3.500000,5.500000
max,38.000000,95.000000,94.000000,90.000000,92.000000,96.000000,8.000000,7.000000

---

## 🛡️ Part 4: Filter Like a Scout

Instead of looking at the whole team, let's isolate specific sub-groups of players using logical filters:

In [41]:
# Filter: Only show players whose position is 'Forward'
forwards = df[df["position"] == "Forward"]
print("⚡ Forwards on Roster:")
print(forwards[["name", "speed", "shooting"]])

⚡ Forwards on Roster:
    name  speed  shooting
0  Artin     92        88
1  Messi     89        96

In [42]:
# Filter: Only show defenders with speed higher than 80
fast_defenders = df[(df["position"] == "Defender") & (df["speed"] > 80)]
print("🛡️ Fast Defensive Lineups:")
print(fast_defenders[["name", "defending", "speed"]])

🛡️ Fast Defensive Lineups:
         name  defending  speed
6     Marcelo         78     86
8     Maldini         94     82
9  Dani Alves         80     88

In [43]:
# Filter: Only show players under age 13
junior_squad = df[df["age"] < 13]
print("👶 Junior Team Selection:")
print(junior_squad[["name", "age", "position"]])

👶 Junior Team Selection:
          name  age    position
0        Artin   11     Forward
3     Maradona   12  Midfielder
5      Iniesta   12  Midfielder
6      Marcelo   11    Defender
10  Beiranvand   12  Goalkeeper

In [ ]:
#midfielders with high stamina
high_stamina_mids = df[(df["stamina"] > 80) & (df["position"] == "Midfielder")]
print("High Stamina Midfielders:")
print(high_stamina_mids[["name", "stamina", "position"]])

High Stamina Midfielders:
       name  stamina    position
3  Maradona       82  Midfielder
4    Zidane       84  Midfielder
5   Iniesta       86  Midfielder

---

## 🧬 Part 5: Add New Columns

We can expand our active DataFrame dynamically! Let's compute two major columns:
1. **Passing Accuracy:** The ratio of completed passes over total attempts.
2. **Needs Rest:** A boolean column that checks if their average stamina is falling low.

In [44]:
# 1. Compute total completed passes over total passes
df["total_completed"] = df["passes_completed"].apply(sum)
df["total_attempts"] = df["total_passes"].apply(sum)
df["passing_accuracy"] = round((df["total_completed"] / df["total_attempts"]) * 100, 1)

# 2. Calculate if they need rest (if their active stamina rating is less than 82)
df["needs_rest"] = df["stamina"] < 82

# Let's view our updated DataFrame columns!
df[["name", "position", "passing_accuracy", "stamina", "needs_rest"]]

           name    position  passing_accuracy  stamina  needs_rest
0         Artin     Forward              90.5       90       False
1         Messi     Forward              96.5       85       False
2   Jahanbakhsh  Midfielder              80.6       80        True
3      Maradona  Midfielder              92.8       82       False
4        Zidane  Midfielder              94.2       84       False
5       Iniesta  Midfielder              95.3       86       False
6       Marcelo    Defender              88.6       88       False
7         Pique    Defender              90.1       80        True
8       Maldini    Defender              92.0       85       False
9    Dani Alves    Defender              89.7       89       False
10   Beiranvand  Goalkeeper              67.0       75        True

## Part 6 — Sorting Like a Professional Scout
A soccer coach rarely looks at players in a random order. Coaches often ask questions like:

Who scored the most goals?
Who has the highest stamina?
Who has the most assists?

Today you'll learn how to sort your team just like a professional scout.

In [ ]:
df.sort_values("goals")

,name,position,age,goals,assists,passes_completed,total_passes,passing,defending,stamina,speed,shooting,total_goals,total_assists,total_completed,total_attempts,passing_accuracy,needs_rest
9,Dani Alves,Defender,13,"[0, 0, 0, -1]","[2, 1, 1, 2]","[32, 35, 30, 33]","[36, 38, 34, 37]",86,80,89,88,72,-1,6,130,145,89.7,False
8,Maldini,Defender,15,"[0, 0, 0, 0]","[0, 0, 1, 0]","[18, 22, 21, 19]","[20, 24, 22, 21]",75,94,85,82,60,0,1,80,87,92.0,False
10,Beiranvand,Goalkeeper,12,"[0, 0, 0, 0]","[0, 0, 0, 0]","[15, 12, 18, 14]","[22, 20, 25, 21]",70,15,75,65,10,0,0,59,88,67.0,True
5,Iniesta,Midfielder,12,"[0, 0, 1, 0]","[2, 1, 1, 1]","[45, 48, 42, 46]","[47, 50, 45, 48]",90,70,86,78,75,1,5,181,190,95.3,False
7,Pique,Defender,14,"[0, 0, 1, 0]","[0, 0, 0, 1]","[22, 24, 20, 25]","[25, 26, 22, 28]",78,88,80,72,65,1,1,91,101,90.1,True
4,Zidane,Midfielder,13,"[0, 1, 0, 0]","[1, 2, 1, 2]","[38, 42, 40, 41]","[40, 45, 42, 44]",92,65,84,80,84,1,6,161,171,94.2,False
6,Marcelo,Defender,11,"[0, 1, 0, 0]","[1, 1, 2, 0]","[30, 32, 28, 34]","[34, 36, 32, 38]",84,78,88,86,70,1,4,124,140,88.6,False
2,Jahanbakhsh,Midfielder,32,"[0, 1, 0, 1]","[1, 0, 1, 0]","[20, 18, 22, 19]","[25, 24, 26, 23]",82,50,80,85,80,2,2,79,98,80.6,True
3,Maradona,Midfielder,12,"[1, 2, 1, 1]","[2, 1, 3, 1]","[35, 38, 32, 36]","[38, 40, 35, 39]",94,40,82,88,92,5,7,141,152,92.8,False
0,Artin,Forward,11,"[2, 1, 0, 3]","[1, 0, 2, 1]","[25, 30, 22, 28]","[28, 32, 26, 30]",85,45,90,92,88,6,4,105,116,90.5,False
1,Messi,Forward,38,"[2, 3, 1, 2]","[1, 1, 2, 0]","[40, 42, 38, 45]","[42, 43, 40, 46]",95,38,85,89,96,8,4,165,171,96.5,False

In [45]:
df.sort_values("goals", ascending=False)

,name,position,age,goals,assists,passes_completed,total_passes,passing,defending,stamina,speed,shooting,total_goals,total_assists,total_completed,total_attempts,passing_accuracy,needs_rest
1,Messi,Forward,38,"[2, 3, 1, 2]","[1, 1, 2, 0]","[40, 42, 38, 45]","[42, 43, 40, 46]",95,38,85,89,96,8,4,165,171,96.5,False
0,Artin,Forward,11,"[2, 1, 0, 3]","[1, 0, 2, 1]","[25, 30, 22, 28]","[28, 32, 26, 30]",85,45,90,92,88,6,4,105,116,90.5,False
3,Maradona,Midfielder,12,"[1, 2, 1, 1]","[2, 1, 3, 1]","[35, 38, 32, 36]","[38, 40, 35, 39]",94,40,82,88,92,5,7,141,152,92.8,False
2,Jahanbakhsh,Midfielder,32,"[0, 1, 0, 1]","[1, 0, 1, 0]","[20, 18, 22, 19]","[25, 24, 26, 23]",82,50,80,85,80,2,2,79,98,80.6,True
4,Zidane,Midfielder,13,"[0, 1, 0, 0]","[1, 2, 1, 2]","[38, 42, 40, 41]","[40, 45, 42, 44]",92,65,84,80,84,1,6,161,171,94.2,False
6,Marcelo,Defender,11,"[0, 1, 0, 0]","[1, 1, 2, 0]","[30, 32, 28, 34]","[34, 36, 32, 38]",84,78,88,86,70,1,4,124,140,88.6,False
5,Iniesta,Midfielder,12,"[0, 0, 1, 0]","[2, 1, 1, 1]","[45, 48, 42, 46]","[47, 50, 45, 48]",90,70,86,78,75,1,5,181,190,95.3,False
7,Pique,Defender,14,"[0, 0, 1, 0]","[0, 0, 0, 1]","[22, 24, 20, 25]","[25, 26, 22, 28]",78,88,80,72,65,1,1,91,101,90.1,True
8,Maldini,Defender,15,"[0, 0, 0, 0]","[0, 0, 1, 0]","[18, 22, 21, 19]","[20, 24, 22, 21]",75,94,85,82,60,0,1,80,87,92.0,False
10,Beiranvand,Goalkeeper,12,"[0, 0, 0, 0]","[0, 0, 0, 0]","[15, 12, 18, 14]","[22, 20, 25, 21]",70,15,75,65,10,0,0,59,88,67.0,True
9,Dani Alves,Defender,13,"[0, 0, 0, -1]","[2, 1, 1, 2]","[32, 35, 30, 33]","[36, 38, 34, 37]",86,80,89,88,72,-1,6,130,145,89.7,False

In [46]:
df.sort_values("stamina", ascending=False)

,name,position,age,goals,assists,passes_completed,total_passes,passing,defending,stamina,speed,shooting,total_goals,total_assists,total_completed,total_attempts,passing_accuracy,needs_rest
0,Artin,Forward,11,"[2, 1, 0, 3]","[1, 0, 2, 1]","[25, 30, 22, 28]","[28, 32, 26, 30]",85,45,90,92,88,6,4,105,116,90.5,False
9,Dani Alves,Defender,13,"[0, 0, 0, -1]","[2, 1, 1, 2]","[32, 35, 30, 33]","[36, 38, 34, 37]",86,80,89,88,72,-1,6,130,145,89.7,False
6,Marcelo,Defender,11,"[0, 1, 0, 0]","[1, 1, 2, 0]","[30, 32, 28, 34]","[34, 36, 32, 38]",84,78,88,86,70,1,4,124,140,88.6,False
5,Iniesta,Midfielder,12,"[0, 0, 1, 0]","[2, 1, 1, 1]","[45, 48, 42, 46]","[47, 50, 45, 48]",90,70,86,78,75,1,5,181,190,95.3,False
1,Messi,Forward,38,"[2, 3, 1, 2]","[1, 1, 2, 0]","[40, 42, 38, 45]","[42, 43, 40, 46]",95,38,85,89,96,8,4,165,171,96.5,False
8,Maldini,Defender,15,"[0, 0, 0, 0]","[0, 0, 1, 0]","[18, 22, 21, 19]","[20, 24, 22, 21]",75,94,85,82,60,0,1,80,87,92.0,False
4,Zidane,Midfielder,13,"[0, 1, 0, 0]","[1, 2, 1, 2]","[38, 42, 40, 41]","[40, 45, 42, 44]",92,65,84,80,84,1,6,161,171,94.2,False
3,Maradona,Midfielder,12,"[1, 2, 1, 1]","[2, 1, 3, 1]","[35, 38, 32, 36]","[38, 40, 35, 39]",94,40,82,88,92,5,7,141,152,92.8,False
2,Jahanbakhsh,Midfielder,32,"[0, 1, 0, 1]","[1, 0, 1, 0]","[20, 18, 22, 19]","[25, 24, 26, 23]",82,50,80,85,80,2,2,79,98,80.6,True
7,Pique,Defender,14,"[0, 0, 1, 0]","[0, 0, 0, 1]","[22, 24, 20, 25]","[25, 26, 22, 28]",78,88,80,72,65,1,1,91,101,90.1,True
10,Beiranvand,Goalkeeper,12,"[0, 0, 0, 0]","[0, 0, 0, 0]","[15, 12, 18, 14]","[22, 20, 25, 21]",70,15,75,65,10,0,0,59,88,67.0,True

In [47]:
df.sort_values("age")

,name,position,age,goals,assists,passes_completed,total_passes,passing,defending,stamina,speed,shooting,total_goals,total_assists,total_completed,total_attempts,passing_accuracy,needs_rest
0,Artin,Forward,11,"[2, 1, 0, 3]","[1, 0, 2, 1]","[25, 30, 22, 28]","[28, 32, 26, 30]",85,45,90,92,88,6,4,105,116,90.5,False
6,Marcelo,Defender,11,"[0, 1, 0, 0]","[1, 1, 2, 0]","[30, 32, 28, 34]","[34, 36, 32, 38]",84,78,88,86,70,1,4,124,140,88.6,False
5,Iniesta,Midfielder,12,"[0, 0, 1, 0]","[2, 1, 1, 1]","[45, 48, 42, 46]","[47, 50, 45, 48]",90,70,86,78,75,1,5,181,190,95.3,False
3,Maradona,Midfielder,12,"[1, 2, 1, 1]","[2, 1, 3, 1]","[35, 38, 32, 36]","[38, 40, 35, 39]",94,40,82,88,92,5,7,141,152,92.8,False
10,Beiranvand,Goalkeeper,12,"[0, 0, 0, 0]","[0, 0, 0, 0]","[15, 12, 18, 14]","[22, 20, 25, 21]",70,15,75,65,10,0,0,59,88,67.0,True
4,Zidane,Midfielder,13,"[0, 1, 0, 0]","[1, 2, 1, 2]","[38, 42, 40, 41]","[40, 45, 42, 44]",92,65,84,80,84,1,6,161,171,94.2,False
9,Dani Alves,Defender,13,"[0, 0, 0, -1]","[2, 1, 1, 2]","[32, 35, 30, 33]","[36, 38, 34, 37]",86,80,89,88,72,-1,6,130,145,89.7,False
7,Pique,Defender,14,"[0, 0, 1, 0]","[0, 0, 0, 1]","[22, 24, 20, 25]","[25, 26, 22, 28]",78,88,80,72,65,1,1,91,101,90.1,True
8,Maldini,Defender,15,"[0, 0, 0, 0]","[0, 0, 1, 0]","[18, 22, 21, 19]","[20, 24, 22, 21]",75,94,85,82,60,0,1,80,87,92.0,False
2,Jahanbakhsh,Midfielder,32,"[0, 1, 0, 1]","[1, 0, 1, 0]","[20, 18, 22, 19]","[25, 24, 26, 23]",82,50,80,85,80,2,2,79,98,80.6,True
1,Messi,Forward,38,"[2, 3, 1, 2]","[1, 1, 2, 0]","[40, 42, 38, 45]","[42, 43, 40, 46]",95,38,85,89,96,8,4,165,171,96.5,False

In [48]:
df.sort_values("assists", ascending=False)

,name,position,age,goals,assists,passes_completed,total_passes,passing,defending,stamina,speed,shooting,total_goals,total_assists,total_completed,total_attempts,passing_accuracy,needs_rest
3,Maradona,Midfielder,12,"[1, 2, 1, 1]","[2, 1, 3, 1]","[35, 38, 32, 36]","[38, 40, 35, 39]",94,40,82,88,92,5,7,141,152,92.8,False
9,Dani Alves,Defender,13,"[0, 0, 0, -1]","[2, 1, 1, 2]","[32, 35, 30, 33]","[36, 38, 34, 37]",86,80,89,88,72,-1,6,130,145,89.7,False
5,Iniesta,Midfielder,12,"[0, 0, 1, 0]","[2, 1, 1, 1]","[45, 48, 42, 46]","[47, 50, 45, 48]",90,70,86,78,75,1,5,181,190,95.3,False
4,Zidane,Midfielder,13,"[0, 1, 0, 0]","[1, 2, 1, 2]","[38, 42, 40, 41]","[40, 45, 42, 44]",92,65,84,80,84,1,6,161,171,94.2,False
1,Messi,Forward,38,"[2, 3, 1, 2]","[1, 1, 2, 0]","[40, 42, 38, 45]","[42, 43, 40, 46]",95,38,85,89,96,8,4,165,171,96.5,False
6,Marcelo,Defender,11,"[0, 1, 0, 0]","[1, 1, 2, 0]","[30, 32, 28, 34]","[34, 36, 32, 38]",84,78,88,86,70,1,4,124,140,88.6,False
0,Artin,Forward,11,"[2, 1, 0, 3]","[1, 0, 2, 1]","[25, 30, 22, 28]","[28, 32, 26, 30]",85,45,90,92,88,6,4,105,116,90.5,False
2,Jahanbakhsh,Midfielder,32,"[0, 1, 0, 1]","[1, 0, 1, 0]","[20, 18, 22, 19]","[25, 24, 26, 23]",82,50,80,85,80,2,2,79,98,80.6,True
8,Maldini,Defender,15,"[0, 0, 0, 0]","[0, 0, 1, 0]","[18, 22, 21, 19]","[20, 24, 22, 21]",75,94,85,82,60,0,1,80,87,92.0,False
7,Pique,Defender,14,"[0, 0, 1, 0]","[0, 0, 0, 1]","[22, 24, 20, 25]","[25, 26, 22, 28]",78,88,80,72,65,1,1,91,101,90.1,True
10,Beiranvand,Goalkeeper,12,"[0, 0, 0, 0]","[0, 0, 0, 0]","[15, 12, 18, 14]","[22, 20, 25, 21]",70,15,75,65,10,0,0,59,88,67.0,True

When sorting by a column containing lists, pandas sorts lexicographically. To sort by the sum of assists, use the `total_assists` column:

In [49]:
df.sort_values("total_assists", ascending=False)

,name,position,age,goals,assists,passes_completed,total_passes,passing,defending,stamina,speed,shooting,total_goals,total_assists,total_completed,total_attempts,passing_accuracy,needs_rest
3,Maradona,Midfielder,12,"[1, 2, 1, 1]","[2, 1, 3, 1]","[35, 38, 32, 36]","[38, 40, 35, 39]",94,40,82,88,92,5,7,141,152,92.8,False
4,Zidane,Midfielder,13,"[0, 1, 0, 0]","[1, 2, 1, 2]","[38, 42, 40, 41]","[40, 45, 42, 44]",92,65,84,80,84,1,6,161,171,94.2,False
9,Dani Alves,Defender,13,"[0, 0, 0, -1]","[2, 1, 1, 2]","[32, 35, 30, 33]","[36, 38, 34, 37]",86,80,89,88,72,-1,6,130,145,89.7,False
5,Iniesta,Midfielder,12,"[0, 0, 1, 0]","[2, 1, 1, 1]","[45, 48, 42, 46]","[47, 50, 45, 48]",90,70,86,78,75,1,5,181,190,95.3,False
6,Marcelo,Defender,11,"[0, 1, 0, 0]","[1, 1, 2, 0]","[30, 32, 28, 34]","[34, 36, 32, 38]",84,78,88,86,70,1,4,124,140,88.6,False
0,Artin,Forward,11,"[2, 1, 0, 3]","[1, 0, 2, 1]","[25, 30, 22, 28]","[28, 32, 26, 30]",85,45,90,92,88,6,4,105,116,90.5,False
1,Messi,Forward,38,"[2, 3, 1, 2]","[1, 1, 2, 0]","[40, 42, 38, 45]","[42, 43, 40, 46]",95,38,85,89,96,8,4,165,171,96.5,False
2,Jahanbakhsh,Midfielder,32,"[0, 1, 0, 1]","[1, 0, 1, 0]","[20, 18, 22, 19]","[25, 24, 26, 23]",82,50,80,85,80,2,2,79,98,80.6,True
7,Pique,Defender,14,"[0, 0, 1, 0]","[0, 0, 0, 1]","[22, 24, 20, 25]","[25, 26, 22, 28]",78,88,80,72,65,1,1,91,101,90.1,True
8,Maldini,Defender,15,"[0, 0, 0, 0]","[0, 0, 1, 0]","[18, 22, 21, 19]","[20, 24, 22, 21]",75,94,85,82,60,0,1,80,87,92.0,False
10,Beiranvand,Goalkeeper,12,"[0, 0, 0, 0]","[0, 0, 0, 0]","[15, 12, 18, 14]","[22, 20, 25, 21]",70,15,75,65,10,0,0,59,88,67.0,True

#### ✏️ Exercise 1

Sort the players by:

goals
assists
age
stamina

Which player appears first each time?

In [50]:
df.sort_values("total_goals", ascending = False)

,name,position,age,goals,assists,passes_completed,total_passes,passing,defending,stamina,speed,shooting,total_goals,total_assists,total_completed,total_attempts,passing_accuracy,needs_rest
1,Messi,Forward,38,"[2, 3, 1, 2]","[1, 1, 2, 0]","[40, 42, 38, 45]","[42, 43, 40, 46]",95,38,85,89,96,8,4,165,171,96.5,False
0,Artin,Forward,11,"[2, 1, 0, 3]","[1, 0, 2, 1]","[25, 30, 22, 28]","[28, 32, 26, 30]",85,45,90,92,88,6,4,105,116,90.5,False
3,Maradona,Midfielder,12,"[1, 2, 1, 1]","[2, 1, 3, 1]","[35, 38, 32, 36]","[38, 40, 35, 39]",94,40,82,88,92,5,7,141,152,92.8,False
2,Jahanbakhsh,Midfielder,32,"[0, 1, 0, 1]","[1, 0, 1, 0]","[20, 18, 22, 19]","[25, 24, 26, 23]",82,50,80,85,80,2,2,79,98,80.6,True
4,Zidane,Midfielder,13,"[0, 1, 0, 0]","[1, 2, 1, 2]","[38, 42, 40, 41]","[40, 45, 42, 44]",92,65,84,80,84,1,6,161,171,94.2,False
5,Iniesta,Midfielder,12,"[0, 0, 1, 0]","[2, 1, 1, 1]","[45, 48, 42, 46]","[47, 50, 45, 48]",90,70,86,78,75,1,5,181,190,95.3,False
6,Marcelo,Defender,11,"[0, 1, 0, 0]","[1, 1, 2, 0]","[30, 32, 28, 34]","[34, 36, 32, 38]",84,78,88,86,70,1,4,124,140,88.6,False
7,Pique,Defender,14,"[0, 0, 1, 0]","[0, 0, 0, 1]","[22, 24, 20, 25]","[25, 26, 22, 28]",78,88,80,72,65,1,1,91,101,90.1,True
8,Maldini,Defender,15,"[0, 0, 0, 0]","[0, 0, 1, 0]","[18, 22, 21, 19]","[20, 24, 22, 21]",75,94,85,82,60,0,1,80,87,92.0,False
10,Beiranvand,Goalkeeper,12,"[0, 0, 0, 0]","[0, 0, 0, 0]","[15, 12, 18, 14]","[22, 20, 25, 21]",70,15,75,65,10,0,0,59,88,67.0,True
9,Dani Alves,Defender,13,"[0, 0, 0, -1]","[2, 1, 1, 2]","[32, 35, 30, 33]","[36, 38, 34, 37]",86,80,89,88,72,-1,6,130,145,89.7,False

In [51]:
df.sort_values("total_assists", ascending = False)

,name,position,age,goals,assists,passes_completed,total_passes,passing,defending,stamina,speed,shooting,total_goals,total_assists,total_completed,total_attempts,passing_accuracy,needs_rest
3,Maradona,Midfielder,12,"[1, 2, 1, 1]","[2, 1, 3, 1]","[35, 38, 32, 36]","[38, 40, 35, 39]",94,40,82,88,92,5,7,141,152,92.8,False
4,Zidane,Midfielder,13,"[0, 1, 0, 0]","[1, 2, 1, 2]","[38, 42, 40, 41]","[40, 45, 42, 44]",92,65,84,80,84,1,6,161,171,94.2,False
9,Dani Alves,Defender,13,"[0, 0, 0, -1]","[2, 1, 1, 2]","[32, 35, 30, 33]","[36, 38, 34, 37]",86,80,89,88,72,-1,6,130,145,89.7,False
5,Iniesta,Midfielder,12,"[0, 0, 1, 0]","[2, 1, 1, 1]","[45, 48, 42, 46]","[47, 50, 45, 48]",90,70,86,78,75,1,5,181,190,95.3,False
6,Marcelo,Defender,11,"[0, 1, 0, 0]","[1, 1, 2, 0]","[30, 32, 28, 34]","[34, 36, 32, 38]",84,78,88,86,70,1,4,124,140,88.6,False
0,Artin,Forward,11,"[2, 1, 0, 3]","[1, 0, 2, 1]","[25, 30, 22, 28]","[28, 32, 26, 30]",85,45,90,92,88,6,4,105,116,90.5,False
1,Messi,Forward,38,"[2, 3, 1, 2]","[1, 1, 2, 0]","[40, 42, 38, 45]","[42, 43, 40, 46]",95,38,85,89,96,8,4,165,171,96.5,False
2,Jahanbakhsh,Midfielder,32,"[0, 1, 0, 1]","[1, 0, 1, 0]","[20, 18, 22, 19]","[25, 24, 26, 23]",82,50,80,85,80,2,2,79,98,80.6,True
7,Pique,Defender,14,"[0, 0, 1, 0]","[0, 0, 0, 1]","[22, 24, 20, 25]","[25, 26, 22, 28]",78,88,80,72,65,1,1,91,101,90.1,True
8,Maldini,Defender,15,"[0, 0, 0, 0]","[0, 0, 1, 0]","[18, 22, 21, 19]","[20, 24, 22, 21]",75,94,85,82,60,0,1,80,87,92.0,False
10,Beiranvand,Goalkeeper,12,"[0, 0, 0, 0]","[0, 0, 0, 0]","[15, 12, 18, 14]","[22, 20, 25, 21]",70,15,75,65,10,0,0,59,88,67.0,True

In [52]:
df.sort_values("age", ascending = False)

,name,position,age,goals,assists,passes_completed,total_passes,passing,defending,stamina,speed,shooting,total_goals,total_assists,total_completed,total_attempts,passing_accuracy,needs_rest
1,Messi,Forward,38,"[2, 3, 1, 2]","[1, 1, 2, 0]","[40, 42, 38, 45]","[42, 43, 40, 46]",95,38,85,89,96,8,4,165,171,96.5,False
2,Jahanbakhsh,Midfielder,32,"[0, 1, 0, 1]","[1, 0, 1, 0]","[20, 18, 22, 19]","[25, 24, 26, 23]",82,50,80,85,80,2,2,79,98,80.6,True
8,Maldini,Defender,15,"[0, 0, 0, 0]","[0, 0, 1, 0]","[18, 22, 21, 19]","[20, 24, 22, 21]",75,94,85,82,60,0,1,80,87,92.0,False
7,Pique,Defender,14,"[0, 0, 1, 0]","[0, 0, 0, 1]","[22, 24, 20, 25]","[25, 26, 22, 28]",78,88,80,72,65,1,1,91,101,90.1,True
4,Zidane,Midfielder,13,"[0, 1, 0, 0]","[1, 2, 1, 2]","[38, 42, 40, 41]","[40, 45, 42, 44]",92,65,84,80,84,1,6,161,171,94.2,False
9,Dani Alves,Defender,13,"[0, 0, 0, -1]","[2, 1, 1, 2]","[32, 35, 30, 33]","[36, 38, 34, 37]",86,80,89,88,72,-1,6,130,145,89.7,False
3,Maradona,Midfielder,12,"[1, 2, 1, 1]","[2, 1, 3, 1]","[35, 38, 32, 36]","[38, 40, 35, 39]",94,40,82,88,92,5,7,141,152,92.8,False
10,Beiranvand,Goalkeeper,12,"[0, 0, 0, 0]","[0, 0, 0, 0]","[15, 12, 18, 14]","[22, 20, 25, 21]",70,15,75,65,10,0,0,59,88,67.0,True
5,Iniesta,Midfielder,12,"[0, 0, 1, 0]","[2, 1, 1, 1]","[45, 48, 42, 46]","[47, 50, 45, 48]",90,70,86,78,75,1,5,181,190,95.3,False
0,Artin,Forward,11,"[2, 1, 0, 3]","[1, 0, 2, 1]","[25, 30, 22, 28]","[28, 32, 26, 30]",85,45,90,92,88,6,4,105,116,90.5,False
6,Marcelo,Defender,11,"[0, 1, 0, 0]","[1, 1, 2, 0]","[30, 32, 28, 34]","[34, 36, 32, 38]",84,78,88,86,70,1,4,124,140,88.6,False

In [53]:
df.sort_values("stamina", ascending = False)

,name,position,age,goals,assists,passes_completed,total_passes,passing,defending,stamina,speed,shooting,total_goals,total_assists,total_completed,total_attempts,passing_accuracy,needs_rest
0,Artin,Forward,11,"[2, 1, 0, 3]","[1, 0, 2, 1]","[25, 30, 22, 28]","[28, 32, 26, 30]",85,45,90,92,88,6,4,105,116,90.5,False
9,Dani Alves,Defender,13,"[0, 0, 0, -1]","[2, 1, 1, 2]","[32, 35, 30, 33]","[36, 38, 34, 37]",86,80,89,88,72,-1,6,130,145,89.7,False
6,Marcelo,Defender,11,"[0, 1, 0, 0]","[1, 1, 2, 0]","[30, 32, 28, 34]","[34, 36, 32, 38]",84,78,88,86,70,1,4,124,140,88.6,False
5,Iniesta,Midfielder,12,"[0, 0, 1, 0]","[2, 1, 1, 1]","[45, 48, 42, 46]","[47, 50, 45, 48]",90,70,86,78,75,1,5,181,190,95.3,False
1,Messi,Forward,38,"[2, 3, 1, 2]","[1, 1, 2, 0]","[40, 42, 38, 45]","[42, 43, 40, 46]",95,38,85,89,96,8,4,165,171,96.5,False
8,Maldini,Defender,15,"[0, 0, 0, 0]","[0, 0, 1, 0]","[18, 22, 21, 19]","[20, 24, 22, 21]",75,94,85,82,60,0,1,80,87,92.0,False
4,Zidane,Midfielder,13,"[0, 1, 0, 0]","[1, 2, 1, 2]","[38, 42, 40, 41]","[40, 45, 42, 44]",92,65,84,80,84,1,6,161,171,94.2,False
3,Maradona,Midfielder,12,"[1, 2, 1, 1]","[2, 1, 3, 1]","[35, 38, 32, 36]","[38, 40, 35, 39]",94,40,82,88,92,5,7,141,152,92.8,False
2,Jahanbakhsh,Midfielder,32,"[0, 1, 0, 1]","[1, 0, 1, 0]","[20, 18, 22, 19]","[25, 24, 26, 23]",82,50,80,85,80,2,2,79,98,80.6,True
7,Pique,Defender,14,"[0, 0, 1, 0]","[0, 0, 0, 1]","[22, 24, 20, 25]","[25, 26, 22, 28]",78,88,80,72,65,1,1,91,101,90.1,True
10,Beiranvand,Goalkeeper,12,"[0, 0, 0, 0]","[0, 0, 0, 0]","[15, 12, 18, 14]","[22, 20, 25, 21]",70,15,75,65,10,0,0,59,88,67.0,True

#### ✏️ Exercise 2

Display only the Top 3 scorers.

(Hint)

In [55]:
df.sort_values("total_goals", ascending = False).head(3)

,name,position,age,goals,assists,passes_completed,total_passes,passing,defending,stamina,speed,shooting,total_goals,total_assists,total_completed,total_attempts,passing_accuracy,needs_rest
1,Messi,Forward,38,"[2, 3, 1, 2]","[1, 1, 2, 0]","[40, 42, 38, 45]","[42, 43, 40, 46]",95,38,85,89,96,8,4,165,171,96.5,False
0,Artin,Forward,11,"[2, 1, 0, 3]","[1, 0, 2, 1]","[25, 30, 22, 28]","[28, 32, 26, 30]",85,45,90,92,88,6,4,105,116,90.5,False
3,Maradona,Midfielder,12,"[1, 2, 1, 1]","[2, 1, 3, 1]","[35, 38, 32, 36]","[38, 40, 35, 39]",94,40,82,88,92,5,7,141,152,92.8,False

In [56]:
df["total_contributions"] = df["total_goals"] + df["total_assists"]
df.sort_values("total_contributions", ascending = False).head(3)

,name,position,age,goals,assists,passes_completed,total_passes,passing,defending,stamina,speed,shooting,total_goals,total_assists,total_completed,total_attempts,passing_accuracy,needs_rest,total_contributions
1,Messi,Forward,38,"[2, 3, 1, 2]","[1, 1, 2, 0]","[40, 42, 38, 45]","[42, 43, 40, 46]",95,38,85,89,96,8,4,165,171,96.5,False,12
3,Maradona,Midfielder,12,"[1, 2, 1, 1]","[2, 1, 3, 1]","[35, 38, 32, 36]","[38, 40, 35, 39]",94,40,82,88,92,5,7,141,152,92.8,False,12
0,Artin,Forward,11,"[2, 1, 0, 3]","[1, 0, 2, 1]","[25, 30, 22, 28]","[28, 32, 26, 30]",85,45,90,92,88,6,4,105,116,90.5,False,10

#### ✏️ Exercise 3

Display the Top 5 players with the highest stamina.

In [57]:
df.sort_values("stamina", ascending = False).head(5)

,name,position,age,goals,assists,passes_completed,total_passes,passing,defending,stamina,speed,shooting,total_goals,total_assists,total_completed,total_attempts,passing_accuracy,needs_rest,total_contributions
0,Artin,Forward,11,"[2, 1, 0, 3]","[1, 0, 2, 1]","[25, 30, 22, 28]","[28, 32, 26, 30]",85,45,90,92,88,6,4,105,116,90.5,False,10
9,Dani Alves,Defender,13,"[0, 0, 0, -1]","[2, 1, 1, 2]","[32, 35, 30, 33]","[36, 38, 34, 37]",86,80,89,88,72,-1,6,130,145,89.7,False,5
6,Marcelo,Defender,11,"[0, 1, 0, 0]","[1, 1, 2, 0]","[30, 32, 28, 34]","[34, 36, 32, 38]",84,78,88,86,70,1,4,124,140,88.6,False,5
5,Iniesta,Midfielder,12,"[0, 0, 1, 0]","[2, 1, 1, 1]","[45, 48, 42, 46]","[47, 50, 45, 48]",90,70,86,78,75,1,5,181,190,95.3,False,6
1,Messi,Forward,38,"[2, 3, 1, 2]","[1, 1, 2, 0]","[40, 42, 38, 45]","[42, 43, 40, 46]",95,38,85,89,96,8,4,165,171,96.5,False,12

## Part 7 — Multi-Level Sorting

Sometimes one statistic is not enough.

Imagine two players have scored 8 goals.

Who should come first?

We can sort using two columns.

Example

In [58]:
df.sort_values(
    by=["total_goals", "total_assists"],
    ascending=False
)

,name,position,age,goals,assists,passes_completed,total_passes,passing,defending,stamina,speed,shooting,total_goals,total_assists,total_completed,total_attempts,passing_accuracy,needs_rest,total_contributions
1,Messi,Forward,38,"[2, 3, 1, 2]","[1, 1, 2, 0]","[40, 42, 38, 45]","[42, 43, 40, 46]",95,38,85,89,96,8,4,165,171,96.5,False,12
0,Artin,Forward,11,"[2, 1, 0, 3]","[1, 0, 2, 1]","[25, 30, 22, 28]","[28, 32, 26, 30]",85,45,90,92,88,6,4,105,116,90.5,False,10
3,Maradona,Midfielder,12,"[1, 2, 1, 1]","[2, 1, 3, 1]","[35, 38, 32, 36]","[38, 40, 35, 39]",94,40,82,88,92,5,7,141,152,92.8,False,12
2,Jahanbakhsh,Midfielder,32,"[0, 1, 0, 1]","[1, 0, 1, 0]","[20, 18, 22, 19]","[25, 24, 26, 23]",82,50,80,85,80,2,2,79,98,80.6,True,4
4,Zidane,Midfielder,13,"[0, 1, 0, 0]","[1, 2, 1, 2]","[38, 42, 40, 41]","[40, 45, 42, 44]",92,65,84,80,84,1,6,161,171,94.2,False,7
5,Iniesta,Midfielder,12,"[0, 0, 1, 0]","[2, 1, 1, 1]","[45, 48, 42, 46]","[47, 50, 45, 48]",90,70,86,78,75,1,5,181,190,95.3,False,6
6,Marcelo,Defender,11,"[0, 1, 0, 0]","[1, 1, 2, 0]","[30, 32, 28, 34]","[34, 36, 32, 38]",84,78,88,86,70,1,4,124,140,88.6,False,5
7,Pique,Defender,14,"[0, 0, 1, 0]","[0, 0, 0, 1]","[22, 24, 20, 25]","[25, 26, 22, 28]",78,88,80,72,65,1,1,91,101,90.1,True,2
8,Maldini,Defender,15,"[0, 0, 0, 0]","[0, 0, 1, 0]","[18, 22, 21, 19]","[20, 24, 22, 21]",75,94,85,82,60,0,1,80,87,92.0,False,1
10,Beiranvand,Goalkeeper,12,"[0, 0, 0, 0]","[0, 0, 0, 0]","[15, 12, 18, 14]","[22, 20, 25, 21]",70,15,75,65,10,0,0,59,88,67.0,True,0
9,Dani Alves,Defender,13,"[0, 0, 0, -1]","[2, 1, 1, 2]","[32, 35, 30, 33]","[36, 38, 34, 37]",86,80,89,88,72,-1,6,130,145,89.7,False,5

Explain:

First sort by goals.

If goals are equal...

Sort by assists.

#### ✏️ Exercise

Sort by

Position
Goals

So that forwards appear together.

Within each position,

show the highest scorers first.

In [59]:
forwards = df[df["position"] == "Forward"]
forwards.sort_values("total_goals", ascending = False).head(3)

,name,position,age,goals,assists,passes_completed,total_passes,passing,defending,stamina,speed,shooting,total_goals,total_assists,total_completed,total_attempts,passing_accuracy,needs_rest,total_contributions
1,Messi,Forward,38,"[2, 3, 1, 2]","[1, 1, 2, 0]","[40, 42, 38, 45]","[42, 43, 40, 46]",95,38,85,89,96,8,4,165,171,96.5,False,12
0,Artin,Forward,11,"[2, 1, 0, 3]","[1, 0, 2, 1]","[25, 30, 22, 28]","[28, 32, 26, 30]",85,45,90,92,88,6,4,105,116,90.5,False,10

### Challenge 7.1
The coach wants three forwards with the highest goals.

Can you find them?

In [60]:
forwards = df[df["position"] == "Forward"]
forwards.sort_values("total_goals", ascending = False).head(3)

,name,position,age,goals,assists,passes_completed,total_passes,passing,defending,stamina,speed,shooting,total_goals,total_assists,total_completed,total_attempts,passing_accuracy,needs_rest,total_contributions
1,Messi,Forward,38,"[2, 3, 1, 2]","[1, 1, 2, 0]","[40, 42, 38, 45]","[42, 43, 40, 46]",95,38,85,89,96,8,4,165,171,96.5,False,12
0,Artin,Forward,11,"[2, 1, 0, 3]","[1, 0, 2, 1]","[25, 30, 22, 28]","[28, 32, 26, 30]",85,45,90,92,88,6,4,105,116,90.5,False,10

###Challenge 7.2
The fitness coach wants every player whose stamina is below 70.

Can you list them?

In [61]:
df["weaklings"] = df["stamina"] < 70
df

,name,position,age,goals,assists,passes_completed,total_passes,passing,defending,stamina,speed,shooting,total_goals,total_assists,total_completed,total_attempts,passing_accuracy,needs_rest,total_contributions,weaklings
0,Artin,Forward,11,"[2, 1, 0, 3]","[1, 0, 2, 1]","[25, 30, 22, 28]","[28, 32, 26, 30]",85,45,90,92,88,6,4,105,116,90.5,False,10,False
1,Messi,Forward,38,"[2, 3, 1, 2]","[1, 1, 2, 0]","[40, 42, 38, 45]","[42, 43, 40, 46]",95,38,85,89,96,8,4,165,171,96.5,False,12,False
2,Jahanbakhsh,Midfielder,32,"[0, 1, 0, 1]","[1, 0, 1, 0]","[20, 18, 22, 19]","[25, 24, 26, 23]",82,50,80,85,80,2,2,79,98,80.6,True,4,False
3,Maradona,Midfielder,12,"[1, 2, 1, 1]","[2, 1, 3, 1]","[35, 38, 32, 36]","[38, 40, 35, 39]",94,40,82,88,92,5,7,141,152,92.8,False,12,False
4,Zidane,Midfielder,13,"[0, 1, 0, 0]","[1, 2, 1, 2]","[38, 42, 40, 41]","[40, 45, 42, 44]",92,65,84,80,84,1,6,161,171,94.2,False,7,False
5,Iniesta,Midfielder,12,"[0, 0, 1, 0]","[2, 1, 1, 1]","[45, 48, 42, 46]","[47, 50, 45, 48]",90,70,86,78,75,1,5,181,190,95.3,False,6,False
6,Marcelo,Defender,11,"[0, 1, 0, 0]","[1, 1, 2, 0]","[30, 32, 28, 34]","[34, 36, 32, 38]",84,78,88,86,70,1,4,124,140,88.6,False,5,False
7,Pique,Defender,14,"[0, 0, 1, 0]","[0, 0, 0, 1]","[22, 24, 20, 25]","[25, 26, 22, 28]",78,88,80,72,65,1,1,91,101,90.1,True,2,False
8,Maldini,Defender,15,"[0, 0, 0, 0]","[0, 0, 1, 0]","[18, 22, 21, 19]","[20, 24, 22, 21]",75,94,85,82,60,0,1,80,87,92.0,False,1,False
9,Dani Alves,Defender,13,"[0, 0, 0, -1]","[2, 1, 1, 2]","[32, 35, 30, 33]","[36, 38, 34, 37]",86,80,89,88,72,-1,6,130,145,89.7,False,5,False
10,Beiranvand,Goalkeeper,12,"[0, 0, 0, 0]","[0, 0, 0, 0]","[15, 12, 18, 14]","[22, 20, 25, 21]",70,15,75,65,10,0,0,59,88,67.0,True,0,False

### Challenge 7.3

The passing coach wants players whose passing accuracy is below 80%.

Can you find them?

In [62]:
df["nates"] = df["passing_accuracy"] < 80
df

,name,position,age,goals,assists,passes_completed,total_passes,passing,defending,stamina,...,shooting,total_goals,total_assists,total_completed,total_attempts,passing_accuracy,needs_rest,total_contributions,weaklings,nates
0,Artin,Forward,11,"[2, 1, 0, 3]","[1, 0, 2, 1]","[25, 30, 22, 28]","[28, 32, 26, 30]",85,45,90,...,88,6,4,105,116,90.5,False,10,False,False
1,Messi,Forward,38,"[2, 3, 1, 2]","[1, 1, 2, 0]","[40, 42, 38, 45]","[42, 43, 40, 46]",95,38,85,...,96,8,4,165,171,96.5,False,12,False,False
2,Jahanbakhsh,Midfielder,32,"[0, 1, 0, 1]","[1, 0, 1, 0]","[20, 18, 22, 19]","[25, 24, 26, 23]",82,50,80,...,80,2,2,79,98,80.6,True,4,False,False
3,Maradona,Midfielder,12,"[1, 2, 1, 1]","[2, 1, 3, 1]","[35, 38, 32, 36]","[38, 40, 35, 39]",94,40,82,...,92,5,7,141,152,92.8,False,12,False,False
4,Zidane,Midfielder,13,"[0, 1, 0, 0]","[1, 2, 1, 2]","[38, 42, 40, 41]","[40, 45, 42, 44]",92,65,84,...,84,1,6,161,171,94.2,False,7,False,False
5,Iniesta,Midfielder,12,"[0, 0, 1, 0]","[2, 1, 1, 1]","[45, 48, 42, 46]","[47, 50, 45, 48]",90,70,86,...,75,1,5,181,190,95.3,False,6,False,False
6,Marcelo,Defender,11,"[0, 1, 0, 0]","[1, 1, 2, 0]","[30, 32, 28, 34]","[34, 36, 32, 38]",84,78,88,...,70,1,4,124,140,88.6,False,5,False,False
7,Pique,Defender,14,"[0, 0, 1, 0]","[0, 0, 0, 1]","[22, 24, 20, 25]","[25, 26, 22, 28]",78,88,80,...,65,1,1,91,101,90.1,True,2,False,False
8,Maldini,Defender,15,"[0, 0, 0, 0]","[0, 0, 1, 0]","[18, 22, 21, 19]","[20, 24, 22, 21]",75,94,85,...,60,0,1,80,87,92.0,False,1,False,False
9,Dani Alves,Defender,13,"[0, 0, 0, -1]","[2, 1, 1, 2]","[32, 35, 30, 33]","[36, 38, 34, 37]",86,80,89,...,72,-1,6,130,145,89.7,False,5,False,False
10,Beiranvand,Goalkeeper,12,"[0, 0, 0, 0]","[0, 0, 0, 0]","[15, 12, 18, 14]","[22, 20, 25, 21]",70,15,75,...,10,0,0,59,88,67.0,True,0,False,True

## 🏆 Boss Challenge – Build the Artin FC Statistics Center

Create a function named analyze_team(players). The function should return a dictionary containing:

In [63]:
{
    "Number of Players": ...,
    "Average Goals": ...,
    "Average Assists": ...,
    "Average Stamina": ...,
    "Top Scorer": ...,
    "Best Passer": ...,
    "Youngest Player": ...,
    "Oldest Player": ...,
    "Need Rest": ...,
    "Need Passing Practice": ...
}

{'Number of Players': Ellipsis,
 'Average Goals': Ellipsis,
 'Average Assists': Ellipsis,
 'Average Stamina': Ellipsis,
 'Top Scorer': Ellipsis,
 'Best Passer': Ellipsis,
 'Youngest Player': Ellipsis,
 'Oldest Player': Ellipsis,
 'Need Rest': Ellipsis,
 'Need Passing Practice': Ellipsis}

Then print a beautiful report.

In [70]:
from coach_toolbox_v2 import *
def analyze_team(players):
# your code here
 #"Number of Players": ...,sad fj
    #"Average Goals": ...,asdf
    #"Average Assists": ...,asdf
    #"Average Stamina": ...,asdf
   # "Top Scorer": ...,lskajdf
   # "Best Passer": ...,asdf
   # "Youngest Player": ...,asdf
   # "Oldest Player": ...,asdf
  #  "Need Rest": ...,sad fh
   # "Need Passing Practice": ...sad fj


    total_players = len(players)

    top_scorer_row = df["total_goals"].idxmax()
    top_scorer_identity = df.loc[top_scorer_row, 'name']


    average_goals = df["total_goals"].mean()
    average_assists = df["total_assists"].mean()
    average_stamina = df["stamina"].mean()
    top_passer_row = df["passing"].idxmax()
    top_passer_identity = df.loc[top_passer_row, 'name']
    youngest_player = df["age"].min()
    oldest_player = df["age"].max()

    need_rest = 0

    for player in players:

        if needs_rest(player):
            need_rest += 1

    needs_passing = 0

    for player in players:

        if needs_passing_practice(player):
            needs_passing += 1

    ready = 0

    for player in players:
        if coach_decision(player) == "Ready for Match.":
            ready += 1




    report = {
        "Number of players": total_players,
        "Number needing rest": need_rest,
        "Number needing passing practice": needs_passing,
        "Number ready for match": ready,
        "Average Goals":  average_goals,
        "Average Assists":average_assists,
        "Average Stamina": average_stamina,
        "Top Scorer": top_scorer_identity,
        "Best Passer": top_passer_identity,
        "Youngest Player": youngest_player,
        "Oldest Player": oldest_player
    }

    return report

In [71]:
analyze_team(Artin_FC_v2)

{'Number of players': 11,
 'Number needing rest': 2,
 'Number needing passing practice': 1,
 'Number ready for match': 8,
 'Average Goals': np.float64(2.1818181818181817),
 'Average Assists': np.float64(3.6363636363636362),
 'Average Stamina': np.float64(84.0),
 'Top Scorer': 'Messi',
 'Best Passer': 'Messi',
 'Youngest Player': 11,
 'Oldest Player': 38}

## Reflection

1- Why is a DataFrame easier to work with than a list of dictionaries?

2- What kinds of questions became easier to answer with pandas?

3- Why is sorting useful for a soccer coach?

4- How can filtering help a scout identify players for different roles?

5- If you were the coach, what new column would you add to improve your team's analysis?

Congratulations! Today you learned how to organize, filter, sort, and analyze soccer data using pandas. Professional data analysts spend much of their time preparing data before creating reports. In the next mission, you will transform all of this information into an interactive analytics dashboard with colorful charts and graphs. Instead of reading tables of numbers, your AI Coach will tell stories through visualizations, making it easier for coaches to understand the strengths and weaknesses of Artin FC at a glance.